In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [5]:
#Want to develop gradient descent
def grad_des(x,y):
    b1_cur=b0_cur=0 #Set-up starting point 
    iteration=1000 #Set-up limit
    n=len(x)
    learning_rate=0.08
    for i in range(iteration):
        y_pred=b0_cur+b1_cur*x
        #predicted y-value for the current b0, b1 vals
        cost=sum([val**2 for val in (y-y_pred)])/n
        #MSE for each step: want to reduce it as we progress
        b1d=-(2/n)*sum(x*(y-y_pred))
        #b1 derivative of SSE(or MSE)
        b0d=-(2/n)*sum(y-y_pred)
        #b0 derivative of SSE(or MSE)
        b1_cur-=b1d*learning_rate
        b0_cur-=b0d*learning_rate
        #Update the coordinates of (b0,b1)
        
        print('b1 {}, b0 {}, cost {} at iteration {}'.format(b1_cur,b0_cur,cost,i))
        #Print progress in each step
x=np.array([1,2,3,4,5])
y=np.array([5,7,9,11,13])
#grad_des(x,y)

In [2]:
#How to treat strings -> dummy variables : 0,1,...
#Caution: 1+2=3 ?? Categorical vars do not relate each other
#There exists some special case: ordinal(can order. e.g. PhD>master>..)
#One hot encoding: Create new column for each category and assign
#Binary variable(0,1) for each variable.
df=pd.read_csv('homeprices1.csv')
df.head(3)

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000

In [ ]:
#Introduce dummy variables

#Now we got dummies. Let's join two data frames

#Drop 'town' and drop one of the dummies: it's causing collinearity
#Why? We can deduce one from other two.
#Let's drop the last one.

#Create regression class

#Drop Y value(price) and create X values

#Create Y 

#Get the linear regression

#Make a prediction

#Score it by comparing actual value and predicted value.

In [4]:
#Introduce dummy variables
dummies=pd.get_dummies(df.town)
dummies.head(2)

monroe township  robinsville  west windsor
0                1            0             0
1                1            0             0

In [5]:
#Now we got dummies. Let's join two data frames
merged=pd.concat([df,dummies],axis='columns')
merged.head(3)

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000                1            0             0
1  monroe township  3000  565000                1            0             0
2  monroe township  3200  610000                1            0             0

In [7]:
#Drop 'town' and drop one of the dummies: it's causing multi-collinearity
#Why? We can deduce one from other two.
#Let's drop the last one.
final=merged.drop(['town','west windsor'],axis='columns')
final.head(3)

area   price  monroe township  robinsville
0  2600  550000                1            0
1  3000  565000                1            0
2  3200  610000                1            0

In [8]:
#Create regression class
from sklearn import linear_model
reg=linear_model.LinearRegression()

In [9]:
#Drop Y value and create X values
X=final.drop(['price'],axis='columns')
X.head(2)

area  monroe township  robinsville
0  2600                1            0
1  3000                1            0

In [10]:
#Create Y 
Y=final.price
Y.head(2)

0    550000
1    565000
Name: price, dtype: int64

In [11]:
#Get the linear regression
reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
# Make a prediction
reg.predict([[2800,0,1]])

array([ 590775.63964739])

In [14]:
reg.predict([[3000,0,0]])

array([ 630482.69189422])

In [14]:
#Score it by comparing actual value and predicted value.
reg.score(X,Y)

0.95739290372218733

In [47]:
#Now, let's use one hot encoding:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=pd.read_csv('homeprices1.csv')
dfle=df
dfle.town=le.fit_transform(dfle.town)
dfle.head(3)

town  area   price
0     0  2600  550000
1     0  3000  565000
2     0  3200  610000

In [49]:
#Only values not data frame-> DataFrame.values
#If only write dfle[['town','area]], we get indexed frame.
X=dfle[['town','area']].values
#Only one column: just arrays
Y=dfle.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [50]:
from sklearn.preprocessing import OneHotEncoder
#Create OneHotEncoder class and teach that cat feat is in the 0-th col
ohe=OneHotEncoder(categorical_features=[0])

In [51]:
X=ohe.fit_transform(X).toarray()
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          2.60000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.00000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.20000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.60000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.00000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.60000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.80000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.30000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.60000000e+03],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          2.60000000e+03],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          2.90000000e+03],
       [  0.00000000e

In [52]:
#Drop zero-th column
X=X[:,1:]
X

array([[  0.00000000e+00,   0.00000000e+00,   2.60000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   3.00000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   3.20000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   3.60000000e+03],
       [  0.00000000e+00,   0.00000000e+00,   4.00000000e+03],
       [  0.00000000e+00,   1.00000000e+00,   2.60000000e+03],
       [  0.00000000e+00,   1.00000000e+00,   2.80000000e+03],
       [  0.00000000e+00,   1.00000000e+00,   3.30000000e+03],
       [  0.00000000e+00,   1.00000000e+00,   3.60000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   2.60000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   2.90000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   3.10000000e+03],
       [  1.00000000e+00,   0.00000000e+00,   3.60000000e+03]])

In [53]:
reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [56]:
reg.predict([[1,0,2800]])

array([ 590775.63964739])