In [1]:
#Multivariable regression
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import linear_model

In [2]:
df=pd.read_csv('homeprices.csv')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [27]:
import math
med_bed=math.floor(df.bedrooms.median())
med_bed

4

In [28]:
#Fill NaN with median(reaonable)
df.bedrooms=df.bedrooms.fillna(med_bed)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [29]:
# Creat Linear regression clss object
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df[['price']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [30]:
reg.coef_

array([[   112.06244194,  23388.88007794,  -3231.71790863]])

In [31]:
reg.intercept_

array([ 221323.0018654])

In [32]:
reg.predict([[3000,3,15]])

array([[ 579201.19929613]])

In [35]:
#Save the regression and load it quickly
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [36]:
mp.predict([[3000,3,15]])

array([[ 579201.19929613]])

In [37]:
#Use joblib to do the same thing
from sklearn.externals import joblib
#Dump it in 'model_joblib'
joblib.dump(reg,'model_joblib')
#Load from 'model_joblib' and record it in mj
mj=joblib.load('model_joblib')
#Use mj to predict
mj.predict([[3000,3,15]])

array([[ 579201.19929613]])

In [9]:
#Next example
from word2number import w2n
df1=pd.read_csv('hiring.csv')
df1.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [11]:
df1.experience=df1.experience.fillna('zero')
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
import math
med_score=math.floor(df1['test_score(out of 10)'].median())
df1['test_score(out of 10)']=df1['test_score(out of 10)'].fillna(0)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    0.0                           7      72000
7     eleven                    7.0                           8      80000

In [16]:
df1.experience=df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    0.0                           7      72000
7          11                    7.0                           8      80000

In [17]:
reg=linear_model.LinearRegression()

In [18]:
reg.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1[['salary($)']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
reg.intercept_

array([ 24823.52310661])

In [21]:
reg.coef_

array([[ 3077.8642085 ,   999.7856246 ,  2118.48834717]])

In [24]:
reg.predict([[12,10,10]])

array([[ 92940.63332619]])