In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import time

plt.style.use(style="seaborn")
%matplotlib inline

In [3]:
df=pd.read_csv('MSFT-1Y-Hourly.csv')

In [10]:
X=df[['close']].copy()
X['target']=X.shift(-1)
X.dropna(inplace=True)

In [23]:
def train_test_split(data,perc):
    data=data.values
    num=int(len(data)*perc)
    train=data[:num,:]
    test=data[num:,:]
    return train, test

In [28]:
train,test=train_test_split(X,0.8)

In [29]:
print(len(train))
print(len(test))
print(len(X))

1401
351
1752


In [36]:
X=train[:,:-1]
y=train[:,-1]

In [37]:
from xgboost import XGBRegressor

In [38]:
model=XGBRegressor(objective="reg:squarederror",n_estimators=1000)
model.fit(X,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=1000, n_jobs=0, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [40]:
test[0]

array([184.08, 183.74])

In [55]:
def xgb_predict(train,val):
    train=np.array(train)
    X,y=train[:,:-1],train[:,-1]
    model=XGBRegressor(objective='reg:squarederror',n_estimators=1000)
    model.fit(X,y)
    val=np.array(val).reshape(1,1)
    pred=model.predict(val)
    return pred[0]

In [56]:
xgb_predict(train,test[0,0])

184.6561

In [58]:
[x for x in train]

[array([132.89, 134.75]),
 array([134.75, 133.88]),
 array([133.88, 133.9 ]),
 array([133.9 , 134.83]),
 array([134.83, 135.48]),
 array([135.48, 135.28]),
 array([135.28, 136.85]),
 array([136.85, 137.81]),
 array([137.81, 138.25]),
 array([138.25, 138.33]),
 array([138.33, 138.16]),
 array([138.16, 138.22]),
 array([138.22, 138.91]),
 array([138.91, 137.58]),
 array([137.58, 137.8 ]),
 array([137.8, 136.7]),
 array([136.7 , 137.41]),
 array([137.41, 137.99]),
 array([137.99, 138.03]),
 array([138.03, 137.69]),
 array([137.69, 136.81]),
 array([136.81, 137.04]),
 array([137.04, 137.08]),
 array([137.08, 136.84]),
 array([136.84, 136.46]),
 array([136.46, 135.45]),
 array([135.45, 135.81]),
 array([135.81, 138.55]),
 array([138.55, 137.95]),
 array([137.95, 138.34]),
 array([138.34, 138.22]),
 array([138.22, 138.31]),
 array([138.31, 138.56]),
 array([138.56, 138.6 ]),
 array([138.6 , 136.38]),
 array([136.38, 135.15]),
 array([135.15, 134.37]),
 array([134.37, 133.91]),
 array([133.91